# This is a basic workflow to help you get started with Actions

name: Print Pi Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  print-pi-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Pi Step
        run: |
          echo pi=`echo "4*a(1)" | bc -l`

     
